Update expressions.yml

diff --git a/.github/workflows/expressions.yml b/.github/workflows/expressions.yml
--- a/.github/workflows/expressions.yml
+++ b/.github/workflows/expressions.yml
@@ -4,14 +4,14 @@ env:
   appName: CounterApp
 
 jobs:
-  build_job:
-   runs-on: window-latest
-   steps:
-    - name: Execute command
-      run: echo "Build automation for application: ${{env.appName}}"
-    - name: executing build step  
-      id: exec
-      run: exit 1
-    - name: Check if the previous step is success of fail
-      run: echo "Running on failure"
-      if: ${{failure() && steps.exec.conlusion == 'failure' }}
+ build_job:
+  runs-on: window-latest
+  steps:
+   - name: Execute command
+     run: echo "Build automation for Application:${{env.appName}}"
+   - name: executing build step  
+     id: exec
+     run: exit 1
+   - name: Check if the previous step is success of fail
+     run: echo "Running on failure"
+     if: ${{failure() && steps.exec.conlusion == 'failure' }}
